# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard_Consultor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1425, 745)
        Dialog.setMinimumSize(QtCore.QSize(1425, 745))
        Dialog.setMaximumSize(QtCore.QSize(1425, 745))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -20, 1431, 781))
        self.label.setStyleSheet("background-color: rgb(228, 237, 246);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 41, 761))
        self.frame.setMinimumSize(QtCore.QSize(25, 0))
        self.frame.setStyleSheet("QFrame{\n"
"    border-top-right-radius: 16px;\n"
"    border-bottom-right-radius: 16px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnQuestionario = QtWidgets.QPushButton(self.frame)
        self.btnQuestionario.setGeometry(QtCore.QRect(10, 540, 121, 28))
        self.btnQuestionario.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/file-sign.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnQuestionario.setObjectName("btnQuestionario")
        self.frameQuetionario = QtWidgets.QFrame(self.frame)
        self.frameQuetionario.setGeometry(QtCore.QRect(10, 560, 141, 0))
        self.frameQuetionario.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}")
        self.frameQuetionario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameQuetionario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQuetionario.setObjectName("frameQuetionario")
        self.btnCadQuest = QtWidgets.QPushButton(self.frameQuetionario)
        self.btnCadQuest.setGeometry(QtCore.QRect(2, 21, 111, 28))
        self.btnCadQuest.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/account-multiple-plus.png);\n"
"    background-repeat: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnCadQuest.setObjectName("btnCadQuest")
        self.btnListQuest = QtWidgets.QPushButton(self.frameQuetionario)
        self.btnListQuest.setGeometry(QtCore.QRect(2, 74, 96, 28))
        self.btnListQuest.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/account-box-multiple.png);\n"
"    background-repeat: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnListQuest.setObjectName("btnListQuest")
        self.bntSair = QtWidgets.QPushButton(self.frame)
        self.bntSair.setGeometry(QtCore.QRect(10, 700, 111, 28))
        self.bntSair.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/door-open.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/door-open(1).png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.bntSair.setObjectName("bntSair")
        self.btnEmpresas = QtWidgets.QPushButton(self.frame)
        self.btnEmpresas.setGeometry(QtCore.QRect(12, 116, 121, 28))
        self.btnEmpresas.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/carbon_industry.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnEmpresas.setObjectName("btnEmpresas")
        self.frameEmpresa = QtWidgets.QFrame(self.frame)
        self.frameEmpresa.setGeometry(QtCore.QRect(10, 140, 141, 0))
        self.frameEmpresa.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}")
        self.frameEmpresa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEmpresa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEmpresa.setObjectName("frameEmpresa")
        self.btnCadEmpresa = QtWidgets.QPushButton(self.frameEmpresa)
        self.btnCadEmpresa.setGeometry(QtCore.QRect(2, 23, 93, 28))
        self.btnCadEmpresa.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/bx_add-to-queue.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnCadEmpresa.setObjectName("btnCadEmpresa")
        self.btnListEmpresa = QtWidgets.QPushButton(self.frameEmpresa)
        self.btnListEmpresa.setGeometry(QtCore.QRect(2, 70, 93, 28))
        self.btnListEmpresa.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/fluent_quiz-new-20-regular.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnListEmpresa.setObjectName("btnListEmpresa")
        self.btnToken = QtWidgets.QPushButton(self.frame)
        self.btnToken.setGeometry(QtCore.QRect(10, 270, 93, 28))
        self.btnToken.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/key.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnToken.setObjectName("btnToken")
        self.btnRelat = QtWidgets.QPushButton(self.frame)
        self.btnRelat.setGeometry(QtCore.QRect(10, 420, 141, 28))
        self.btnRelat.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/carbon_industry-1.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnRelat.setObjectName("btnRelat")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.label_29.setStyleSheet("image: url(:/icones/scanawe2a.png);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 41, 28))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    image: url(:/icones/format-list-bulleted-square.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border-radius: 10px;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(170, 68, 1251, 671))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777142))
        self.frame_2.setStyleSheet("background-color: rgb(228, 237, 246);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Paginas = QtWidgets.QStackedWidget(self.frame_2)
        self.Paginas.setStyleSheet("background-color: rgb(228, 237, 246);\n"
"border-radius: 10px;")
        self.Paginas.setObjectName("Paginas")
        self.PageHome = QtWidgets.QWidget()
        self.PageHome.setObjectName("PageHome")
        self.label_4 = QtWidgets.QLabel(self.PageHome)
        self.label_4.setGeometry(QtCore.QRect(-10, 10, 1231, 31))
        self.label_4.setObjectName("label_4")
        self.frame_13 = QtWidgets.QFrame(self.PageHome)
        self.frame_13.setGeometry(QtCore.QRect(10, 220, 821, 321))
        self.frame_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_27 = QtWidgets.QLabel(self.frame_13)
        self.label_27.setGeometry(QtCore.QRect(70, 10, 651, 281))
        self.label_27.setStyleSheet("image: url(:/icones/Empresas.jpg);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_3 = QtWidgets.QLabel(self.PageHome)
        self.label_3.setGeometry(QtCore.QRect(920, 70, 271, 491))
        self.label_3.setStyleSheet("image: url(:/icones/Proximos_quetionarios.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame_14 = QtWidgets.QFrame(self.PageHome)
        self.frame_14.setGeometry(QtCore.QRect(10, 100, 821, 80))
        self.frame_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_28 = QtWidgets.QLabel(self.frame_14)
        self.label_28.setGeometry(QtCore.QRect(60, -27, 701, 131))
        self.label_28.setStyleSheet("image: url(:/icones/Status.jpg);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.numEmpresas = QtWidgets.QLabel(self.frame_14)
        self.numEmpresas.setGeometry(QtCore.QRect(134, 40, 61, 21))
        self.numEmpresas.setStyleSheet("QLabel{\n"
"    color: rgb(34, 90, 229);\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}")
        self.numEmpresas.setObjectName("numEmpresas")
        self.Paginas.addWidget(self.PageHome)
        self.EmpresaList = QtWidgets.QWidget()
        self.EmpresaList.setStyleSheet("")
        self.EmpresaList.setObjectName("EmpresaList")
        self.TabelaEmpresas = QtWidgets.QTableWidget(self.EmpresaList)
        self.TabelaEmpresas.setGeometry(QtCore.QRect(10, 126, 1201, 521))
        self.TabelaEmpresas.setStyleSheet("QTableWidget { \n"
"        background-color: rgb(228, 237, 246);\n"
"        border-radius: 10px;\n"
"}\n"
"\n"
"    QTableWidget::item{\n"
"        color: rgb(0, 0, 0);\n"
"        background-color: rgb(228, 237, 246);\n"
"        margin-top: 5px;\n"
"        border: none;\n"
"        border-radius: 10px;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected{\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(130, 153, 255);\n"
"    }\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(5, 37, 69);\n"
"    padding: 4px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 10pt;\n"
"    border-bottom: none;\n"
"    border-right: none;\n"
"    border-left: none;\n"
"}\n"
"\n"
"")
        self.TabelaEmpresas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaEmpresas.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TabelaEmpresas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaEmpresas.setObjectName("TabelaEmpresas")
        self.TabelaEmpresas.setColumnCount(10)
        self.TabelaEmpresas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaEmpresas.setHorizontalHeaderItem(9, item)
        self.frame_6 = QtWidgets.QFrame(self.EmpresaList)
        self.frame_6.setGeometry(QtCore.QRect(0, -18, 1215, 131))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 37, 69);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(0, 30, 1221, 31))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.btnPesqEmpresa = QtWidgets.QPushButton(self.EmpresaList)
        self.btnPesqEmpresa.setGeometry(QtCore.QRect(690, 71, 41, 28))
        self.btnPesqEmpresa.setStyleSheet("QPushButton{    \n"
"    image: url(:/icones/magnify (1).png);\n"
"    border: none;\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    image: url(:/icones/magnify.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border: 1.5px solid rgb(255, 255, 255);\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnPesqEmpresa.setText("")
        self.btnPesqEmpresa.setObjectName("btnPesqEmpresa")
        self.PesqEmpresa = QtWidgets.QLineEdit(self.EmpresaList)
        self.PesqEmpresa.setGeometry(QtCore.QRect(490, 70, 191, 31))
        self.PesqEmpresa.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 1px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.PesqEmpresa.setInputMask("")
        self.PesqEmpresa.setText("")
        self.PesqEmpresa.setObjectName("PesqEmpresa")
        self.btnExcluiEmpresa = QtWidgets.QPushButton(self.EmpresaList)
        self.btnExcluiEmpresa.setGeometry(QtCore.QRect(1080, 70, 121, 31))
        self.btnExcluiEmpresa.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/delete.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/delete (1).png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btnExcluiEmpresa.setObjectName("btnExcluiEmpresa")
        self.btnAlteraEmpresa = QtWidgets.QPushButton(self.EmpresaList)
        self.btnAlteraEmpresa.setGeometry(QtCore.QRect(20, 70, 121, 31))
        self.btnAlteraEmpresa.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/pencil (1).png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/pencil.png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btnAlteraEmpresa.setObjectName("btnAlteraEmpresa")
        self.Paginas.addWidget(self.EmpresaList)
        self.EmpresaCad = QtWidgets.QWidget()
        self.EmpresaCad.setStyleSheet("QWidget{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(228, 237, 246);\n"
"}\n"
"QLineEdit {\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.EmpresaCad.setObjectName("EmpresaCad")
        self.frame_5 = QtWidgets.QFrame(self.EmpresaCad)
        self.frame_5.setGeometry(QtCore.QRect(60, -1, 1111, 651))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 301, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.nomeEmpresa = QtWidgets.QLineEdit(self.frame_5)
        self.nomeEmpresa.setGeometry(QtCore.QRect(60, 120, 311, 31))
        self.nomeEmpresa.setObjectName("nomeEmpresa")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(60, 90, 151, 21))
        self.label_7.setObjectName("label_7")
        self.siglaEmpresa = QtWidgets.QLineEdit(self.frame_5)
        self.siglaEmpresa.setGeometry(QtCore.QRect(400, 120, 211, 31))
        self.siglaEmpresa.setObjectName("siglaEmpresa")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(400, 90, 151, 21))
        self.label_8.setObjectName("label_8")
        self.cnpj = QtWidgets.QLineEdit(self.frame_5)
        self.cnpj.setGeometry(QtCore.QRect(640, 120, 251, 31))
        self.cnpj.setObjectName("cnpj")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(640, 90, 151, 21))
        self.label_9.setObjectName("label_9")
        self.btnCadEmpresas = QtWidgets.QPushButton(self.frame_5)
        self.btnCadEmpresas.setGeometry(QtCore.QRect(940, 600, 121, 31))
        self.btnCadEmpresas.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnCadEmpresas.setObjectName("btnCadEmpresas")
        self.btnLimpEmpresa = QtWidgets.QPushButton(self.frame_5)
        self.btnLimpEmpresa.setGeometry(QtCore.QRect(60, 600, 93, 28))
        self.btnLimpEmpresa.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color: rgb(85, 0, 255);\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnLimpEmpresa.setObjectName("btnLimpEmpresa")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setGeometry(QtCore.QRect(59, 180, 1001, 211))
        self.frame_4.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.rua = QtWidgets.QLineEdit(self.frame_4)
        self.rua.setGeometry(QtCore.QRect(19, 150, 271, 31))
        self.rua.setObjectName("rua")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(19, 125, 151, 21))
        self.label_11.setStyleSheet("border: none")
        self.label_11.setObjectName("label_11")
        self.cidade = QtWidgets.QLineEdit(self.frame_4)
        self.cidade.setGeometry(QtCore.QRect(300, 150, 291, 31))
        self.cidade.setObjectName("cidade")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(300, 125, 151, 21))
        self.label_12.setStyleSheet("border: none")
        self.label_12.setObjectName("label_12")
        self.numero = QtWidgets.QLineEdit(self.frame_4)
        self.numero.setGeometry(QtCore.QRect(300, 60, 121, 31))
        self.numero.setObjectName("numero")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(300, 36, 151, 21))
        self.label_13.setStyleSheet("border: none")
        self.label_13.setObjectName("label_13")
        self.bairro = QtWidgets.QLineEdit(self.frame_4)
        self.bairro.setGeometry(QtCore.QRect(430, 60, 291, 31))
        self.bairro.setObjectName("bairro")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(430, 35, 151, 21))
        self.label_14.setStyleSheet("border: none")
        self.label_14.setObjectName("label_14")
        self.cep = QtWidgets.QLineEdit(self.frame_4)
        self.cep.setGeometry(QtCore.QRect(20, 60, 271, 31))
        self.cep.setObjectName("cep")
        self.complemento = QtWidgets.QLineEdit(self.frame_4)
        self.complemento.setGeometry(QtCore.QRect(730, 60, 251, 31))
        self.complemento.setObjectName("complemento")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(730, 38, 151, 21))
        self.label_15.setStyleSheet("border: none")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(20, 36, 151, 21))
        self.label_16.setStyleSheet("border: none")
        self.label_16.setObjectName("label_16")
        self.estado = QtWidgets.QLineEdit(self.frame_4)
        self.estado.setGeometry(QtCore.QRect(600, 150, 101, 31))
        self.estado.setObjectName("estado")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(600, 128, 151, 21))
        self.label_18.setStyleSheet("border: none")
        self.label_18.setObjectName("label_18")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setGeometry(QtCore.QRect(70, 160, 91, 40))
        self.frame_8.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"font-size: 14px;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setGeometry(QtCore.QRect(60, 420, 1001, 161))
        self.frame_9.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.usuarioGestor = QtWidgets.QLineEdit(self.frame_9)
        self.usuarioGestor.setGeometry(QtCore.QRect(470, 110, 251, 31))
        self.usuarioGestor.setObjectName("usuarioGestor")
        self.senhaGestor = QtWidgets.QLineEdit(self.frame_9)
        self.senhaGestor.setGeometry(QtCore.QRect(730, 110, 241, 31))
        self.senhaGestor.setObjectName("senhaGestor")
        self.nomeGestor = QtWidgets.QLineEdit(self.frame_9)
        self.nomeGestor.setGeometry(QtCore.QRect(20, 50, 361, 31))
        self.nomeGestor.setObjectName("nomeGestor")
        self.emailGestor = QtWidgets.QLineEdit(self.frame_9)
        self.emailGestor.setGeometry(QtCore.QRect(20, 110, 441, 31))
        self.emailGestor.setObjectName("emailGestor")
        self.cpfGestor = QtWidgets.QLineEdit(self.frame_9)
        self.cpfGestor.setGeometry(QtCore.QRect(390, 50, 281, 31))
        self.cpfGestor.setObjectName("cpfGestor")
        self.telGestor = QtWidgets.QLineEdit(self.frame_9)
        self.telGestor.setGeometry(QtCore.QRect(680, 50, 291, 31))
        self.telGestor.setObjectName("telGestor")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(20, 24, 151, 21))
        self.label_20.setStyleSheet("border: none")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(390, 24, 151, 21))
        self.label_21.setStyleSheet("border: none")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setGeometry(QtCore.QRect(680, 24, 151, 21))
        self.label_22.setStyleSheet("border: none")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        self.label_23.setGeometry(QtCore.QRect(20, 85, 151, 21))
        self.label_23.setStyleSheet("border: none")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setGeometry(QtCore.QRect(470, 85, 151, 21))
        self.label_24.setStyleSheet("border: none")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_9)
        self.label_25.setGeometry(QtCore.QRect(730, 85, 151, 21))
        self.label_25.setStyleSheet("border: none")
        self.label_25.setObjectName("label_25")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setGeometry(QtCore.QRect(70, 400, 161, 40))
        self.frame_10.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"font-size: 14px;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.Paginas.addWidget(self.EmpresaCad)
        self.GerarRelat = QtWidgets.QWidget()
        self.GerarRelat.setObjectName("GerarRelat")
        self.frame_15 = QtWidgets.QFrame(self.GerarRelat)
        self.frame_15.setGeometry(QtCore.QRect(270, 40, 631, 551))
        self.frame_15.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_30 = QtWidgets.QLabel(self.frame_15)
        self.label_30.setGeometry(QtCore.QRect(60, 190, 501, 271))
        self.label_30.setStyleSheet("image: url(:/icones/Desenvolvimento.jpg);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        self.label_31.setGeometry(QtCore.QRect(0, 50, 631, 71))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_15)
        self.label_32.setGeometry(QtCore.QRect(160, 500, 301, 21))
        self.label_32.setObjectName("label_32")
        self.Paginas.addWidget(self.GerarRelat)
        self.Questionario = QtWidgets.QWidget()
        self.Questionario.setObjectName("Questionario")
        self.frame_16 = QtWidgets.QFrame(self.Questionario)
        self.frame_16.setGeometry(QtCore.QRect(270, 40, 631, 551))
        self.frame_16.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_33 = QtWidgets.QLabel(self.frame_16)
        self.label_33.setGeometry(QtCore.QRect(60, 190, 501, 271))
        self.label_33.setStyleSheet("image: url(:/icones/Desenvolvimento.jpg);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_16)
        self.label_34.setGeometry(QtCore.QRect(0, 50, 631, 71))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_16)
        self.label_35.setGeometry(QtCore.QRect(160, 500, 301, 21))
        self.label_35.setObjectName("label_35")
        self.Paginas.addWidget(self.Questionario)
        self.GerarToken = QtWidgets.QWidget()
        self.GerarToken.setObjectName("GerarToken")
        self.TabelaGerarToken = QtWidgets.QTableWidget(self.GerarToken)
        self.TabelaGerarToken.setGeometry(QtCore.QRect(10, 130, 1191, 511))
        self.TabelaGerarToken.setStyleSheet("QTableWidget { \n"
"        background-color: rgb(228, 237, 246);\n"
"        border-radius: 10px;\n"
"}\n"
"\n"
"    QTableWidget::item{\n"
"        color: rgb(0, 0, 0);\n"
"        background-color: rgb(228, 237, 246);\n"
"        margin-top: 5px;\n"
"        border: none;\n"
"        border-radius: 10px;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected{\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(130, 153, 255);\n"
"    }\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(5, 37, 69);\n"
"    padding: 4px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 10pt;\n"
"    border-bottom: none;\n"
"    border-right: none;\n"
"    border-left: none;\n"
"}")
        self.TabelaGerarToken.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaGerarToken.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TabelaGerarToken.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaGerarToken.setObjectName("TabelaGerarToken")
        self.TabelaGerarToken.setColumnCount(3)
        self.TabelaGerarToken.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaGerarToken.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaGerarToken.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaGerarToken.setHorizontalHeaderItem(2, item)
        self.frame_7 = QtWidgets.QFrame(self.GerarToken)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1217, 111))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: rgb(5, 37, 69);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(0, 19, 1216, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.btnSiglaEmpresa = QtWidgets.QComboBox(self.frame_7)
        self.btnSiglaEmpresa.setGeometry(QtCore.QRect(95, 59, 151, 30))
        self.btnSiglaEmpresa.setStyleSheet("QComboBox{\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 255, 255);\n"
"}\n"
"    QComboBox::drop-down {\n"
"   \n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3p;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icones/arrow-down-drop-circle-outline(1).png);\n"
"}")
        self.btnSiglaEmpresa.setObjectName("btnSiglaEmpresa")
        self.btnSiglaEmpresa.addItem("")
        self.btnSiglaEmpresa.setItemText(0, "")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.btnGerarTooken = QtWidgets.QPushButton(self.frame_7)
        self.btnGerarTooken.setGeometry(QtCore.QRect(1090, 60, 93, 28))
        self.btnGerarTooken.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(255, 255, 255);;\n"
"}")
        self.btnGerarTooken.setObjectName("btnGerarTooken")
        self.btnPesqColabEmp = QtWidgets.QPushButton(self.frame_7)
        self.btnPesqColabEmp.setGeometry(QtCore.QRect(253, 60, 41, 28))
        self.btnPesqColabEmp.setStyleSheet("QPushButton{    \n"
"    image: url(:/icones/magnify (1).png);\n"
"    border: none;\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    image: url(:/icones/magnify.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border: 1.5px solid rgb(255, 255, 255);\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnPesqColabEmp.setText("")
        self.btnPesqColabEmp.setObjectName("btnPesqColabEmp")
        self.Paginas.addWidget(self.GerarToken)
        self.verticalLayout.addWidget(self.Paginas)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(170, 5, 1241, 61))
        self.frame_3.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnHome = QtWidgets.QPushButton(self.frame_3)
        self.btnHome.setGeometry(QtCore.QRect(30, 16, 93, 28))
        self.btnHome.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/bxs_dashboard.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnHome.setObjectName("btnHome")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(510, -24, 181, 111))
        self.label_26.setStyleSheet("image: url(:/icones/scanawe2a.png);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(979, 6, 251, 47))
        self.frame_11.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(190, 3, 52, 41))
        self.frame_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/icones/account_36.png);\n"
"background-repeat: none;\n"
"background-position: center;\n"
"border-radius: 18px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.NomeUsuario = QtWidgets.QLabel(self.frame_11)
        self.NomeUsuario.setGeometry(QtCore.QRect(20, 7, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.NomeUsuario.setFont(font)
        self.NomeUsuario.setText("")
        self.NomeUsuario.setObjectName("NomeUsuario")
        self.label.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Dialog)
        self.Paginas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnQuestionario.setText(_translate("Dialog", "     Questionario"))
        self.btnCadQuest.setText(_translate("Dialog", "Cadastra"))
        self.btnListQuest.setText(_translate("Dialog", "Lista"))
        self.bntSair.setText(_translate("Dialog", "Sair"))
        self.btnEmpresas.setText(_translate("Dialog", "    Empresas"))
        self.btnCadEmpresa.setText(_translate("Dialog", "Cadastar"))
        self.btnListEmpresa.setText(_translate("Dialog", "Lista"))
        self.btnToken.setText(_translate("Dialog", "     Token"))
        self.btnRelat.setText(_translate("Dialog", "    Gerar Relatório"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#052545;\">Dashboard</span></p></body></html>"))
        self.numEmpresas.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#000000;\">0</span></p></body></html>"))
        item = self.TabelaEmpresas.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Sigla"))
        item = self.TabelaEmpresas.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.TabelaEmpresas.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "CNPJ"))
        item = self.TabelaEmpresas.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Estado"))
        item = self.TabelaEmpresas.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Cidade"))
        item = self.TabelaEmpresas.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Bairro"))
        item = self.TabelaEmpresas.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Rua"))
        item = self.TabelaEmpresas.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Número"))
        item = self.TabelaEmpresas.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "CEP"))
        item = self.TabelaEmpresas.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Complemento"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Lista de Empresas</span></p></body></html>"))
        self.PesqEmpresa.setPlaceholderText(_translate("Dialog", "Pesquisa"))
        self.btnExcluiEmpresa.setText(_translate("Dialog", "Excluir"))
        self.btnAlteraEmpresa.setText(_translate("Dialog", "Alterar"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Cadastro de Empresas</span></p><p><br/></p></body></html>"))
        self.nomeEmpresa.setPlaceholderText(_translate("Dialog", "NOME"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Nome da Empresa:</span></p></body></html>"))
        self.siglaEmpresa.setPlaceholderText(_translate("Dialog", "SIGLA"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Sigla da Empresa:</span></p></body></html>"))
        self.cnpj.setInputMask(_translate("Dialog", "00.000.000/0000-00"))
        self.cnpj.setPlaceholderText(_translate("Dialog", "CNPJ"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">CNPJ:</span></p></body></html>"))
        self.btnCadEmpresas.setText(_translate("Dialog", "Cadastrar"))
        self.btnLimpEmpresa.setText(_translate("Dialog", "Limpar Campos"))
        self.rua.setPlaceholderText(_translate("Dialog", "RUA"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Rua:</span></p></body></html>"))
        self.cidade.setPlaceholderText(_translate("Dialog", "CIDADE"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Cidade:</span></p></body></html>"))
        self.numero.setPlaceholderText(_translate("Dialog", "NÚMERO"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Número:</span></p></body></html>"))
        self.bairro.setPlaceholderText(_translate("Dialog", "BAIRRO"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Bairro:</span></p></body></html>"))
        self.cep.setInputMask(_translate("Dialog", "00000-000"))
        self.cep.setPlaceholderText(_translate("Dialog", "CEP"))
        self.complemento.setPlaceholderText(_translate("Dialog", "COMPLEMENTO"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Complemento:</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">CEP:</span></p></body></html>"))
        self.estado.setPlaceholderText(_translate("Dialog", "ESTADO"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Estado:</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "Endereço"))
        self.usuarioGestor.setPlaceholderText(_translate("Dialog", "USÚARIO"))
        self.senhaGestor.setPlaceholderText(_translate("Dialog", "SENHA"))
        self.nomeGestor.setPlaceholderText(_translate("Dialog", "NOME"))
        self.emailGestor.setPlaceholderText(_translate("Dialog", "E-MAIL"))
        self.cpfGestor.setInputMask(_translate("Dialog", "000.000.000-00"))
        self.cpfGestor.setPlaceholderText(_translate("Dialog", "CPF"))
        self.telGestor.setInputMask(_translate("Dialog", "(00) 0 0000-0000"))
        self.telGestor.setPlaceholderText(_translate("Dialog", "TELEFONE"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Nome Gestor:</span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">CPF:</span></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Telefone:</span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">E-mail:</span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Usúario:</span></p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Senha:</span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "Gestor da Empresa"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Pagina em Desenvolvimento</span></p></body></html>"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Contato: consultorscanawe@gmail.com</span></p></body></html>"))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Pagina em Desenvolvimento</span></p></body></html>"))
        self.label_35.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Contato: consultorscanawe@gmail.com</span></p></body></html>"))
        item = self.TabelaGerarToken.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nome"))
        item = self.TabelaGerarToken.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Setor"))
        item = self.TabelaGerarToken.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Token"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Gerar Token</span></p><p align=\"center\"><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Empresa: </span></p></body></html>"))
        self.btnGerarTooken.setText(_translate("Dialog", "Gerar Token"))
        self.btnHome.setText(_translate("Dialog", "Home"))
import Img.icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
