# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard_Gestor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os, sys
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
from numpy import random


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1425, 745)
        Dialog.setMinimumSize(QtCore.QSize(1425, 745))
        Dialog.setMaximumSize(QtCore.QSize(1425, 745))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -20, 1431, 781))
        self.label.setStyleSheet("background-color: rgb(228, 237, 246);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 41, 761))
        self.frame.setMinimumSize(QtCore.QSize(25, 0))
        self.frame.setStyleSheet("QFrame{\n"
"    border-top-right-radius: 16px;\n"
"    border-bottom-right-radius: 16px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnEmpresas = QtWidgets.QPushButton(self.frame)
        self.btnEmpresas.setGeometry(QtCore.QRect(12, 106, 121, 28))
        self.btnEmpresas.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/carbon_industry.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnEmpresas.setObjectName("btnEmpresas")
        self.frameSetor = QtWidgets.QFrame(self.frame)
        self.frameSetor.setGeometry(QtCore.QRect(10, 130, 141, 0))
        self.frameSetor.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}")
        self.frameSetor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSetor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSetor.setObjectName("frameSetor")
        self.btnCadSetor = QtWidgets.QPushButton(self.frameSetor)
        self.btnCadSetor.setGeometry(QtCore.QRect(10, 23, 111, 28))
        self.btnCadSetor.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/bx_add-to-queue.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnCadSetor.setObjectName("btnCadSetor")
        self.btnListSetor = QtWidgets.QPushButton(self.frameSetor)
        self.btnListSetor.setGeometry(QtCore.QRect(10, 70, 111, 28))
        self.btnListSetor.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/clipboard-list-outline.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnListSetor.setObjectName("btnListSetor")
        self.frameColab = QtWidgets.QFrame(self.frame)
        self.frameColab.setGeometry(QtCore.QRect(10, 340, 141, 0))
        self.frameColab.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}")
        self.frameColab.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameColab.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColab.setObjectName("frameColab")
        self.btnCadColab = QtWidgets.QPushButton(self.frameColab)
        self.btnCadColab.setGeometry(QtCore.QRect(10, 21, 111, 28))
        self.btnCadColab.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/account-multiple-plus.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnCadColab.setObjectName("btnCadColab")
        self.btnListColab = QtWidgets.QPushButton(self.frameColab)
        self.btnListColab.setGeometry(QtCore.QRect(10, 74, 111, 28))
        self.btnListColab.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/account-box-multiple.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnListColab.setObjectName("btnListColab")
        self.btnColab = QtWidgets.QPushButton(self.frame)
        self.btnColab.setGeometry(QtCore.QRect(10, 320, 121, 28))
        self.btnColab.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/account.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnColab.setObjectName("btnColab")
        self.bntSair = QtWidgets.QPushButton(self.frame)
        self.bntSair.setGeometry(QtCore.QRect(10, 690, 111, 28))
        self.bntSair.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/door-open.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/door-open(1).png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.bntSair.setObjectName("bntSair")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.label_20.setStyleSheet("image: url(:/icones/scanawe2a.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.btnRelat = QtWidgets.QPushButton(self.frame)
        self.btnRelat.setGeometry(QtCore.QRect(10, 510, 111, 28))
        self.btnRelat.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/carbon_industry-1.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnRelat.setObjectName("btnRelat")
        self.frameSetor.raise_()
        self.btnEmpresas.raise_()
        self.frameColab.raise_()
        self.btnColab.raise_()
        self.bntSair.raise_()
        self.label_20.raise_()
        self.btnRelat.raise_()
        self.Menu = QtWidgets.QPushButton(Dialog)
        self.Menu.setGeometry(QtCore.QRect(10, 10, 41, 28))
        self.Menu.setStyleSheet("QPushButton{\n"
"    image: url(:/icones/format-list-bulleted-square.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border-radius: 10px;\n"
"}")
        self.Menu.setText("")
        self.Menu.setObjectName("Menu")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(170, 70, 1241, 681))
        self.frame_2.setStyleSheet("background-color: rgb(228, 237, 246);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Paginas = QtWidgets.QStackedWidget(self.frame_2)
        self.Paginas.setStyleSheet("")
        self.Paginas.setObjectName("Paginas")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.label_19 = QtWidgets.QLabel(self.pageHome)
        self.label_19.setGeometry(QtCore.QRect(-10, 0, 1231, 41))
        self.label_19.setObjectName("label_19")
        self.frame_4 = QtWidgets.QFrame(self.pageHome)
        self.frame_4.setGeometry(QtCore.QRect(200, 80, 801, 91))
        self.frame_4.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(80, -50, 681, 191))
        self.label_21.setStyleSheet("image: url(:/icones/Status_Gestor.jpg);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.NumColab = QtWidgets.QLabel(self.frame_4)
        self.NumColab.setGeometry(QtCore.QRect(150, 49, 55, 17))
        self.NumColab.setStyleSheet("QLabel{\n"
"    color: rgb(34, 90, 229);\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}")
        self.NumColab.setObjectName("NumColab")
        self.NumSetor = QtWidgets.QLabel(self.frame_4)
        self.NumSetor.setGeometry(QtCore.QRect(394, 49, 55, 18))
        self.NumSetor.setStyleSheet("QLabel{\n"
"    color: rgb(241, 198, 91);\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}")
        self.NumSetor.setObjectName("NumSetor")
        self.frame_9 = QtWidgets.QFrame(self.pageHome)
        self.frame_9.setGeometry(QtCore.QRect(90, 250, 1041, 361))
        self.frame_9.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setGeometry(QtCore.QRect(40, 10, 931, 331))
        self.label_22.setStyleSheet("image: url(:/icones/Empresas.jpg);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.Paginas.addWidget(self.pageHome)
        self.SetorCad = QtWidgets.QWidget()
        self.SetorCad.setObjectName("SetorCad")
        self.frame_5 = QtWidgets.QFrame(self.SetorCad)
        self.frame_5.setGeometry(QtCore.QRect(240, 20, 731, 601))
        self.frame_5.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(160, 30, 401, 51))
        self.label_9.setObjectName("label_9")
        self.nomeSetorCad = QtWidgets.QLineEdit(self.frame_5)
        self.nomeSetorCad.setGeometry(QtCore.QRect(20, 133, 311, 31))
        self.nomeSetorCad.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.nomeSetorCad.setObjectName("nomeSetorCad")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 131, 21))
        self.label_10.setObjectName("label_10")
        self.textEdit = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit.setGeometry(QtCore.QRect(30, 383, 651, 101))
        self.textEdit.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.textEdit.setObjectName("textEdit")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(30, 350, 161, 21))
        self.label_11.setObjectName("label_11")
        self.bntCadSetor = QtWidgets.QPushButton(self.frame_5)
        self.bntCadSetor.setGeometry(QtCore.QRect(30, 530, 651, 31))
        self.bntCadSetor.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.bntCadSetor.setObjectName("bntCadSetor")
        self.nomeSetorCad_2 = QtWidgets.QLineEdit(self.frame_5)
        self.nomeSetorCad_2.setGeometry(QtCore.QRect(370, 133, 311, 31))
        self.nomeSetorCad_2.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.nomeSetorCad_2.setObjectName("nomeSetorCad_2")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(370, 110, 131, 21))
        self.label_12.setObjectName("label_12")
        self.locSetorCad = QtWidgets.QLineEdit(self.frame_5)
        self.locSetorCad.setGeometry(QtCore.QRect(20, 223, 311, 31))
        self.locSetorCad.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.locSetorCad.setObjectName("locSetorCad")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(20, 200, 131, 21))
        self.label_13.setObjectName("label_13")
        self.SetorPaiCad = QtWidgets.QLineEdit(self.frame_5)
        self.SetorPaiCad.setGeometry(QtCore.QRect(370, 223, 311, 31))
        self.SetorPaiCad.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.SetorPaiCad.setObjectName("SetorPaiCad")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(370, 200, 131, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(233, 303, 131, 21))
        self.label_15.setObjectName("label_15")
        self.RamalSetorCad = QtWidgets.QLineEdit(self.frame_5)
        self.RamalSetorCad.setGeometry(QtCore.QRect(290, 300, 131, 31))
        self.RamalSetorCad.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.RamalSetorCad.setObjectName("RamalSetorCad")
        self.Paginas.addWidget(self.SetorCad)
        self.ListaSetor = QtWidgets.QWidget()
        self.ListaSetor.setObjectName("ListaSetor")
        self.TabelaSetor = QtWidgets.QTableWidget(self.ListaSetor)
        self.TabelaSetor.setGeometry(QtCore.QRect(0, 146, 1217, 505))
        self.TabelaSetor.setStyleSheet("QTableWidget { \n"
"        background-color: rgb(228, 237, 246);\n"
"        border-radius: 10px;\n"
"}\n"
"\n"
"    QTableWidget::item{\n"
"        color: rgb(0, 0, 0);\n"
"        background-color: rgb(228, 237, 246);\n"
"        margin-top: 5px;\n"
"        border: none;\n"
"        border-radius: 10px;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected{\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(130, 153, 255);\n"
"    }\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(5, 37, 69);\n"
"    padding: 4px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 10pt;\n"
"    border-bottom: none;\n"
"    border-right: none;\n"
"    border-left: none;\n"
"}\n"
"\n"
"")
        self.TabelaSetor.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaSetor.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TabelaSetor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaSetor.setObjectName("TabelaSetor")
        self.TabelaSetor.setColumnCount(6)
        self.TabelaSetor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaSetor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaSetor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaSetor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaSetor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaSetor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaSetor.setHorizontalHeaderItem(5, item)
        self.btnAlteraSetor = QtWidgets.QPushButton(self.ListaSetor)
        self.btnAlteraSetor.setGeometry(QtCore.QRect(20, 90, 121, 31))
        self.btnAlteraSetor.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/pencil (1).png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/pencil.png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btnAlteraSetor.setObjectName("btnAlteraSetor")
        self.frame_7 = QtWidgets.QFrame(self.ListaSetor)
        self.frame_7.setGeometry(QtCore.QRect(0, 2, 1217, 131))
        self.frame_7.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 37, 69);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(0, 20, 1221, 31))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.btnExcluiSetor = QtWidgets.QPushButton(self.ListaSetor)
        self.btnExcluiSetor.setGeometry(QtCore.QRect(1080, 90, 121, 31))
        self.btnExcluiSetor.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/delete.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/delete (1).png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btnExcluiSetor.setObjectName("btnExcluiSetor")
        self.PesqSetor = QtWidgets.QLineEdit(self.ListaSetor)
        self.PesqSetor.setGeometry(QtCore.QRect(490, 90, 191, 31))
        self.PesqSetor.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 1px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.PesqSetor.setInputMask("")
        self.PesqSetor.setText("")
        self.PesqSetor.setObjectName("PesqSetor")
        self.btnPesqSetor = QtWidgets.QPushButton(self.ListaSetor)
        self.btnPesqSetor.setGeometry(QtCore.QRect(690, 90, 41, 28))
        self.btnPesqSetor.setStyleSheet("QPushButton{    \n"
"    image: url(:/icones/magnify (1).png);\n"
"    border: none;\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    image: url(:/icones/magnify.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnPesqSetor.setText("")
        self.btnPesqSetor.setObjectName("btnPesqSetor")
        self.frame_7.raise_()
        self.TabelaSetor.raise_()
        self.btnAlteraSetor.raise_()
        self.btnExcluiSetor.raise_()
        self.PesqSetor.raise_()
        self.btnPesqSetor.raise_()
        self.Paginas.addWidget(self.ListaSetor)
        self.PessoaCad = QtWidgets.QWidget()
        self.PessoaCad.setStyleSheet("QWidget{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(228, 237, 246);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 0px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}")
        self.PessoaCad.setObjectName("PessoaCad")
        self.frame_8 = QtWidgets.QFrame(self.PessoaCad)
        self.frame_8.setGeometry(QtCore.QRect(160, 60, 891, 461))
        self.frame_8.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 891, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.NomeCadPS = QtWidgets.QLineEdit(self.frame_8)
        self.NomeCadPS.setGeometry(QtCore.QRect(50, 130, 461, 31))
        self.NomeCadPS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NomeCadPS.setObjectName("NomeCadPS")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(530, 100, 61, 21))
        self.label_4.setObjectName("label_4")
        self.CPFCadPS = QtWidgets.QLineEdit(self.frame_8)
        self.CPFCadPS.setGeometry(QtCore.QRect(530, 130, 301, 31))
        self.CPFCadPS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CPFCadPS.setMaxLength(14)
        self.CPFCadPS.setObjectName("CPFCadPS")
        self.EmailCadPS = QtWidgets.QLineEdit(self.frame_8)
        self.EmailCadPS.setGeometry(QtCore.QRect(50, 220, 491, 31))
        self.EmailCadPS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EmailCadPS.setObjectName("EmailCadPS")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(50, 190, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setGeometry(QtCore.QRect(560, 190, 81, 21))
        self.label_5.setObjectName("label_5")
        self.TelCadPS = QtWidgets.QLineEdit(self.frame_8)
        self.TelCadPS.setGeometry(QtCore.QRect(560, 220, 271, 31))
        self.TelCadPS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TelCadPS.setObjectName("TelCadPS")
        self.CargoCadPS = QtWidgets.QLineEdit(self.frame_8)
        self.CargoCadPS.setGeometry(QtCore.QRect(50, 320, 291, 31))
        self.CargoCadPS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CargoCadPS.setObjectName("CargoCadPS")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setGeometry(QtCore.QRect(50, 286, 61, 31))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(380, 293, 81, 21))
        self.label_8.setObjectName("label_8")
        self.SetorCadPS = QtWidgets.QComboBox(self.frame_8)
        self.SetorCadPS.setGeometry(QtCore.QRect(380, 321, 202, 31))
        self.SetorCadPS.setStyleSheet("QComboBox{\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 255, 255);\n"
"}\n"
"    QComboBox::drop-down {\n"
"   \n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3p;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icones/arrow-down-drop-circle-outline(1).png);\n"
"}")
        self.SetorCadPS.setObjectName("SetorCadPS")
        self.SetorCadPS.addItem("")
        self.SetorCadPS.setItemText(0, "")
        self.bntCadastarPS = QtWidgets.QPushButton(self.frame_8)
        self.bntCadastarPS.setGeometry(QtCore.QRect(720, 410, 131, 31))
        self.bntCadastarPS.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.bntCadastarPS.setObjectName("bntCadastarPS")
        self.bntLimparPS = QtWidgets.QPushButton(self.frame_8)
        self.bntLimparPS.setGeometry(QtCore.QRect(20, 410, 131, 31))
        self.bntLimparPS.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.bntLimparPS.setObjectName("bntLimparPS")
        self.Paginas.addWidget(self.PessoaCad)
        self.ListaPessoa = QtWidgets.QWidget()
        self.ListaPessoa.setObjectName("ListaPessoa")
        self.PesqPessoa = QtWidgets.QLineEdit(self.ListaPessoa)
        self.PesqPessoa.setGeometry(QtCore.QRect(490, 90, 191, 31))
        self.PesqPessoa.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 1px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.PesqPessoa.setInputMask("")
        self.PesqPessoa.setText("")
        self.PesqPessoa.setObjectName("PesqPessoa")
        self.btnPesqPessoa = QtWidgets.QPushButton(self.ListaPessoa)
        self.btnPesqPessoa.setGeometry(QtCore.QRect(690, 90, 41, 28))
        self.btnPesqPessoa.setStyleSheet("QPushButton{    \n"
"    image: url(:/icones/magnify (1).png);\n"
"    border: none;\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    image: url(:/icones/magnify.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnPesqPessoa.setText("")
        self.btnPesqPessoa.setObjectName("btnPesqPessoa")
        self.btnAlteraPessoa = QtWidgets.QPushButton(self.ListaPessoa)
        self.btnAlteraPessoa.setGeometry(QtCore.QRect(20, 90, 121, 31))
        self.btnAlteraPessoa.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/pencil (1).png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/pencil.png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btnAlteraPessoa.setObjectName("btnAlteraPessoa")
        self.btnExcluiPessoa = QtWidgets.QPushButton(self.ListaPessoa)
        self.btnExcluiPessoa.setGeometry(QtCore.QRect(1080, 90, 121, 31))
        self.btnExcluiPessoa.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/delete.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/icones/delete (1).png);\n"
"    background-repeat: none;\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btnExcluiPessoa.setObjectName("btnExcluiPessoa")
        self.ListaPessoas = QtWidgets.QTableWidget(self.ListaPessoa)
        self.ListaPessoas.setGeometry(QtCore.QRect(5, 150, 1211, 501))
        self.ListaPessoas.setStyleSheet("QTableWidget { \n"
"        background-color: rgb(228, 237, 246);\n"
"        border-radius: 10px;\n"
"}\n"
"\n"
"    QTableWidget::item{\n"
"        color: rgb(0, 0, 0);\n"
"        background-color: rgb(228, 237, 246);\n"
"        margin-top: 5px;\n"
"        border: none;\n"
"        border-radius: 10px;\n"
"    }\n"
"\n"
"    QTableWidget::item:selected{\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(130, 153, 255);\n"
"    }\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(5, 37, 69);\n"
"    padding: 4px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 10pt;\n"
"    border-bottom: none;\n"
"    border-right: none;\n"
"    border-left: none;\n"
"}\n"
"")
        self.ListaPessoas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ListaPessoas.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ListaPessoas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ListaPessoas.setObjectName("ListaPessoas")
        self.ListaPessoas.setColumnCount(5)
        self.ListaPessoas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ListaPessoas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ListaPessoas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ListaPessoas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ListaPessoas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ListaPessoas.setHorizontalHeaderItem(4, item)
        self.frame_6 = QtWidgets.QFrame(self.ListaPessoa)
        self.frame_6.setGeometry(QtCore.QRect(9, 0, 1209, 131))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 37, 69);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(0, 20, 1221, 31))
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.frame_6.raise_()
        self.PesqPessoa.raise_()
        self.btnPesqPessoa.raise_()
        self.btnAlteraPessoa.raise_()
        self.btnExcluiPessoa.raise_()
        self.ListaPessoas.raise_()
        self.Paginas.addWidget(self.ListaPessoa)
        self.Relatorio = QtWidgets.QWidget()
        self.Relatorio.setObjectName("Relatorio")
        self.label_23 = QtWidgets.QLabel(self.Relatorio)
        self.label_23.setGeometry(QtCore.QRect(-10, 20, 1241, 21))
        self.label_23.setObjectName("label_23")
        self.PaginasQuestao = QtWidgets.QStackedWidget(self.Relatorio)
        self.PaginasQuestao.setGeometry(QtCore.QRect(-10, 150, 1231, 491))
        self.PaginasQuestao.setObjectName("PaginasQuestao")
        self.Questao1 = QtWidgets.QWidget()
        self.Questao1.setObjectName("Questao1")
        self.frame_10 = QtWidgets.QFrame(self.Questao1)
        self.frame_10.setGeometry(QtCore.QRect(40, 40, 1161, 401))
        self.frame_10.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")

        self.horizontalLayoyt_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayoyt_4.setObjectName("layoutGrafico")
        #Graficos
        self.figure = plt.figure()
        self.canvas = FigureCanvasQTAgg(self.figure)
        self.horizontalLayoyt_4.addWidget(self.canvas)

        self.PaginasQuestao.addWidget(self.Questao1)
        self.comboBox = QtWidgets.QComboBox(self.Relatorio)
        self.comboBox.setGeometry(QtCore.QRect(490, 90, 161, 31))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 255, 255);\n"
"}\n"
"    QComboBox::drop-down {\n"
"   \n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3p;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icones/arrow-down-drop-circle-outline(1).png);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btnPesqQuestao = QtWidgets.QPushButton(self.Relatorio)
        self.btnPesqQuestao.setGeometry(QtCore.QRect(660, 92, 41, 28))
        self.btnPesqQuestao.setStyleSheet("QPushButton{    \n"
"    image: url(:/icones/magnify (1).png);\n"
"    border: none;\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    image: url(:/icones/magnify.png);\n"
"    background-color: rgb(5, 37, 69);\n"
"    border: 1.5px solid  rgb(255, 255, 255);\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnPesqQuestao.setText("")
        self.btnPesqQuestao.setObjectName("btnPesqQuestao")
        self.Paginas.addWidget(self.Relatorio)
        self.verticalLayout.addWidget(self.Paginas)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(170, 6, 1241, 61))
        self.frame_3.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnHome = QtWidgets.QPushButton(self.frame_3)
        self.btnHome.setGeometry(QtCore.QRect(30, 16, 93, 28))
        self.btnHome.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icones/bxs_dashboard.png);\n"
"    background-repeat: none;\n"
"    background-position: center;\n"
"    background-position: left;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    color: rgb(5, 37, 69);\n"
"    border-radius: 5px;  \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnHome.setObjectName("btnHome")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(510, -24, 181, 111))
        self.label_17.setStyleSheet("image: url(:/icones/scanawe2a.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(981, 7, 251, 47))
        self.frame_11.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(190, 3, 52, 41))
        self.frame_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/icones/account_36.png);\n"
"background-repeat: none;\n"
"background-position: center;\n"
"border-radius: 18px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.NomeUsuario = QtWidgets.QLabel(self.frame_11)
        self.NomeUsuario.setGeometry(QtCore.QRect(20, 7, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.NomeUsuario.setFont(font)
        self.NomeUsuario.setText("")
        self.NomeUsuario.setObjectName("NomeUsuario")
        self.label.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.Menu.raise_()

        self.retranslateUi(Dialog)
        self.Paginas.setCurrentIndex(0)
        self.PaginasQuestao.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnEmpresas.setText(_translate("Dialog", "Setor"))
        self.btnCadSetor.setText(_translate("Dialog", "Cadastar"))
        self.btnListSetor.setText(_translate("Dialog", "Lista"))
        self.btnCadColab.setText(_translate("Dialog", "Cadastra"))
        self.btnListColab.setText(_translate("Dialog", "Lista"))
        self.btnColab.setText(_translate("Dialog", "     Colaborador"))
        self.bntSair.setText(_translate("Dialog", "Sair"))
        self.btnRelat.setText(_translate("Dialog", "   Relatório"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#052545;\">Dashboard</span></p></body></html>"))
        self.NumColab.setText(_translate("Dialog", "0"))
        self.NumSetor.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Cadastra Setor</span></p></body></html>"))
        self.nomeSetorCad.setPlaceholderText(_translate("Dialog", "Nome do Setor"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Nome do Setor:</span></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "Descrição do Setor"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Descrição do Setor:</span></p></body></html>"))
        self.bntCadSetor.setText(_translate("Dialog", "Cadastar"))
        self.nomeSetorCad_2.setPlaceholderText(_translate("Dialog", "Sigla Setor"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Sigla do Setor:</span></p></body></html>"))
        self.locSetorCad.setPlaceholderText(_translate("Dialog", "Localização"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Localização:</span></p></body></html>"))
        self.SetorPaiCad.setPlaceholderText(_translate("Dialog", "Setor Pai"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Setor Pai:</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Ramal:</span></p></body></html>"))
        self.RamalSetorCad.setPlaceholderText(_translate("Dialog", "Ramal"))
        item = self.TabelaSetor.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Sigla"))
        item = self.TabelaSetor.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.TabelaSetor.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Localização"))
        item = self.TabelaSetor.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Ramal"))
        item = self.TabelaSetor.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Setor Pai"))
        item = self.TabelaSetor.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Descrição"))
        self.btnAlteraSetor.setText(_translate("Dialog", "Alterar"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Lista de Setor</span></p><p align=\"center\"><br/></p></body></html>"))
        self.btnExcluiSetor.setText(_translate("Dialog", "Excluir"))
        self.PesqSetor.setPlaceholderText(_translate("Dialog", "Pesquisa"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">  Cadastro de Colaborador</span></p><p><br/></p></body></html>"))
        self.NomeCadPS.setPlaceholderText(_translate("Dialog", "NOME"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Nome: </span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">CPF:</span></p></body></html>"))
        self.CPFCadPS.setInputMask(_translate("Dialog", "000.000.000-00"))
        self.CPFCadPS.setText(_translate("Dialog", "..-"))
        self.CPFCadPS.setPlaceholderText(_translate("Dialog", "CPF"))
        self.EmailCadPS.setPlaceholderText(_translate("Dialog", "E-MAIL"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">E-Mail</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Telefone:</span></p></body></html>"))
        self.TelCadPS.setInputMask(_translate("Dialog", "(00) 0 0000-0000"))
        self.TelCadPS.setText(_translate("Dialog", "()  -"))
        self.TelCadPS.setPlaceholderText(_translate("Dialog", "TELEFONE"))
        self.CargoCadPS.setPlaceholderText(_translate("Dialog", "CARGO"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Cargo:</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Setor:</span></p></body></html>"))
        self.bntCadastarPS.setText(_translate("Dialog", "Cadastrar"))
        self.bntLimparPS.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">Limpar</span></p></body></html>"))
        self.bntLimparPS.setText(_translate("Dialog", "Limpar Campos"))
        self.PesqPessoa.setPlaceholderText(_translate("Dialog", "Pesquisa"))
        self.btnAlteraPessoa.setText(_translate("Dialog", "Alterar"))
        self.btnExcluiPessoa.setText(_translate("Dialog", "Excluir"))
        item = self.ListaPessoas.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.ListaPessoas.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.ListaPessoas.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "E-mail"))
        item = self.ListaPessoas.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Telefone"))
        item = self.ListaPessoas.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Cargo"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Lista de Colaboradores</span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#052545;\">Gráfico Relatório</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "Questão 1 - Fase 1"))
        self.comboBox.setItemText(1, _translate("Dialog", "Questão 2 - Fase 1"))
        self.comboBox.setItemText(2, _translate("Dialog", "Questão 3 - Fase 1"))
        self.comboBox.setItemText(3, _translate("Dialog", "Questão 4 - Fase 1"))
        self.comboBox.setItemText(4, _translate("Dialog", "Questão 1 - Fase 2"))
        self.comboBox.setItemText(5, _translate("Dialog", "Questão 2 - Fase 2"))
        self.comboBox.setItemText(6, _translate("Dialog", "Questão 3 - Fase 2"))
        self.comboBox.setItemText(7, _translate("Dialog", "Questão 4 - Fase 2"))
        self.comboBox.setItemText(8, _translate("Dialog", "Questão 5 - Fase 2"))
        self.comboBox.setItemText(9, _translate("Dialog", "Questão 6 - Fase 2"))
        self.comboBox.setItemText(10, _translate("Dialog", "Questão 7 - Fase 2"))
        self.comboBox.setItemText(11, _translate("Dialog", "Questão 8 - Fase 2"))
        self.comboBox.setItemText(12, _translate("Dialog", "Questão 9 - Fase 2"))
        self.comboBox.setItemText(13, _translate("Dialog", "Questão 10 - Fase 2"))
        self.btnHome.setText(_translate("Dialog", "Home"))
import Img.icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
