# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Token.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 720)
        Dialog.setMinimumSize(QtCore.QSize(1100, 720))
        Dialog.setMaximumSize(QtCore.QSize(1100, 720))
        self.fromaLogin = QtWidgets.QLabel(Dialog)
        self.fromaLogin.setGeometry(QtCore.QRect(-10, -10, 1181, 758))
        self.fromaLogin.setStyleSheet("background-color: rgb(228, 237, 246);")
        self.fromaLogin.setText("")
        self.fromaLogin.setObjectName("fromaLogin")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(670, 0, 521, 721))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btnToken = QtWidgets.QPushButton(Dialog)
        self.btnToken.setGeometry(QtCore.QRect(740, 560, 291, 41))
        self.btnToken.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnToken.setObjectName("btnToken")
        self.inputUsuario = QtWidgets.QLineEdit(Dialog)
        self.inputUsuario.setGeometry(QtCore.QRect(740, 410, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(11)
        self.inputUsuario.setFont(font)
        self.inputUsuario.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.inputUsuario.setText("")
        self.inputUsuario.setObjectName("inputUsuario")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(740, 380, 171, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(720, 40, 341, 171))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(710, 190, 361, 91))
        self.label_4.setObjectName("label_4")
        self.buttonLogin = QtWidgets.QPushButton(Dialog)
        self.buttonLogin.setGeometry(QtCore.QRect(870, 450, 161, 28))
        self.buttonLogin.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    color: rgb(21, 75, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.buttonLogin.setObjectName("buttonLogin")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 10, 551, 461))
        self.label_5.setStyleSheet("image: url(:/icones/scanawe1a.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 690, 171, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(660, 0, 521, 721))
        self.label_7.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"border-radius: 30px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.fromaLogin.raise_()
        self.label_7.raise_()
        self.label_2.raise_()
        self.btnToken.raise_()
        self.inputUsuario.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.buttonLogin.raise_()
        self.label_5.raise_()
        self.label_6.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setWhatsThis(_translate("Dialog", "<html>border-radius: 10px 0 0 10px;</html>"))
        self.btnToken.setText(_translate("Dialog", "Entrar"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Insira seu Token:</span><span style=\" font-size:14pt;\"/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Olá, seja bem-vindo ao </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">nosso quastionário!</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#707070;\">Para iniciar informe seu token que </span></p><p align=\"center\"><span style=\" font-size:11pt; color:#707070;\">te enviamos no seu e-mail empresarial, </span></p><p align=\"center\"><span style=\" font-size:11pt; color:#707070;\">ele garantirá a sua confidencialidade.</span></p></body></html>"))
        self.buttonLogin.setText(_translate("Dialog", "Entrar com Login"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\"> Copyright © Scanawe </span></p></body></html>"))
        self.label_7.setWhatsThis(_translate("Dialog", "<html>border-radius: 10px 0 0 10px;</html>"))
import Img.icones
import Img.img_acessibilidade


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
