# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_User.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 720)
        Dialog.setMinimumSize(QtCore.QSize(1100, 720))
        Dialog.setMaximumSize(QtCore.QSize(1100, 720))
        self.fromaLogin = QtWidgets.QLabel(Dialog)
        self.fromaLogin.setGeometry(QtCore.QRect(-40, -10, 1181, 758))
        self.fromaLogin.setStyleSheet("background-color: rgb(228, 237, 246);")
        self.fromaLogin.setText("")
        self.fromaLogin.setObjectName("fromaLogin")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(640, 0, 521, 721))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(670, 160, 181, 81))
        self.label.setStyleSheet("QLabel{\n"
"    font-weight: 500;\n"
"    margin-bottom: 2.5rem;\n"
"    position: relative;\n"
"    font-size: 2em;\n"
"}\n"
"\n"
"Qlabel::before{\n"
"    content: \'\';\n"
"    position: absolute;\n"
"    height: 4px;\n"
"    width: 25px;\n"
"    bottom: 3px;\n"
"    left: 0;\n"
"    border-radius: 8px;\n"
"    background: #2B4C7E;\n"
"}")
        self.label.setObjectName("label")
        self.inputUsuario = QtWidgets.QLineEdit(Dialog)
        self.inputUsuario.setGeometry(QtCore.QRect(760, 330, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(11)
        self.inputUsuario.setFont(font)
        self.inputUsuario.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.inputUsuario.setText("")
        self.inputUsuario.setObjectName("inputUsuario")
        self.inputSenha = QtWidgets.QLineEdit(Dialog)
        self.inputSenha.setGeometry(QtCore.QRect(760, 400, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(11)
        self.inputSenha.setFont(font)
        self.inputSenha.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid rgb(55, 55, 55);\n"
"    border-color: rgb(6, 31, 255);\n"
"}")
        self.inputSenha.setText("")
        self.inputSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputSenha.setObjectName("inputSenha")
        self.btnEntrar = QtWidgets.QPushButton(Dialog)
        self.btnEntrar.setGeometry(QtCore.QRect(840, 480, 211, 41))
        self.btnEntrar.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(5, 37, 69);\n"
"    color: white;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover{\n"
"    border: 1.5px solid rgb(5, 37, 69);\n"
"    background-color: none;\n"
"    color: rgb(5, 37, 69);\n"
"}")
        self.btnEntrar.setObjectName("btnEntrar")
        self.labelUsuario = QtWidgets.QLabel(Dialog)
        self.labelUsuario.setGeometry(QtCore.QRect(670, 335, 83, 28))
        self.labelUsuario.setObjectName("labelUsuario")
        self.labelUsuario_2 = QtWidgets.QLabel(Dialog)
        self.labelUsuario_2.setGeometry(QtCore.QRect(680, 405, 83, 28))
        self.labelUsuario_2.setObjectName("labelUsuario_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(630, 0, 71, 721))
        self.label_5.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"border-radius: 30px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 690, 171, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 0, 551, 461))
        self.label_7.setStyleSheet("image: url(:/icones/scanawe1a.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.btnToken = QtWidgets.QPushButton(Dialog)
        self.btnToken.setGeometry(QtCore.QRect(930, 20, 161, 28))
        self.btnToken.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    color: rgb(21, 75, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btnToken.setObjectName("btnToken")
        self.fromaLogin.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.inputUsuario.raise_()
        self.inputSenha.raise_()
        self.btnEntrar.raise_()
        self.labelUsuario.raise_()
        self.labelUsuario_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.btnToken.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setWhatsThis(_translate("Dialog", "<html>border-radius: 10px 0 0 10px;</html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Login</span></p></body></html>"))
        self.btnEntrar.setText(_translate("Dialog", "Entrar"))
        self.labelUsuario.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Usuário:</span></p></body></html>"))
        self.labelUsuario_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Senha:</span></p></body></html>"))
        self.label_5.setWhatsThis(_translate("Dialog", "<html>border-radius: 10px 0 0 10px;</html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\"> Copyright © Scanawe </span></p></body></html>"))
        self.btnToken.setText(_translate("Dialog", "Entar com Token"))
import Img.icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
